config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :warriors
  resources :fights, only: [:index, :show, :new, :create]

end

app/models/accessory.rb
class Accessory < ApplicationRecord
  has_many :fights_as_accessory_1, inverse_of: :accessory_1, class_name: 'Fight', foreign_key: 'accessory_1_id'
  has_many :fights_as_accessory_2, inverse_of: :accessory_2, class_name: 'Fight', foreign_key: 'accessory_2_id'

  validates :category, :name, :effect, presence: true

  def self.list_names
    Accessory.all.map { |acc| acc.name }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :fighter_1, class_name: 'Warrior', foreign_key: 'fighter_1_id'
  belongs_to :fighter_2, class_name: 'Warrior', foreign_key: 'fighter_2_id'
  belongs_to :accessory_1, class_name: 'Accessory', foreign_key: 'accessory_1_id'
  belongs_to :accessory_2, class_name: 'Accessory', foreign_key: 'accessory_2_id'

  validates :fighter_1, :fighter_2, presence: true
  attribute :strokes, :integer, default: 0
end

app/models/warrior.rb
class Warrior < ApplicationRecord
  has_many :fights_as_fighter_1, inverse_of: :fighter_1, class_name: 'Fight', foreign_key: 'fighter_1_id'
  has_many :fights_as_fighter_2, inverse_of: :fighter_2, class_name: 'Fight', foreign_key: 'fighter_2_id'

  validates :name, :life_points, :strength, :xp, presence: true
  validates :life_points, numericality: { only_integer: true, less_than_or_equal_to: 200 }
  validates :strength, numericality: { only_integer: true, less_than_or_equal_to: 10 }
  validates :xp, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  attribute :xp, :integer, default: 0
  has_one_attached :avatar

  def fights_nb
    self.fights_as_fighter_1.count + self.fights_as_fighter_2.count
  end

  def wins_nb
    Fight.all.where(winner: self.name).count
  end

  def wins_rate
    rate = (wins_nb / fights_nb.to_f * 100).round(1)
    rate.nan? ? 0 : rate
  end

  def update_xp(strokes)
    new_xp = self.xp + (strokes / 2)
    self.update(xp: new_xp)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show]
  before_action :set_fighters, only: [:create]
  before_action :set_accessories, only: [:create]

  def index
    @fights = Fight.all
  end

  def show
    @fighter_1 = Warrior.find(@fight.fighter_1_id)
    @fighter_2 = Warrior.find(@fight.fighter_2_id)
    @accessory_1 = Accessory.find(@fight.accessory_1_id)
    @accessory_2 = Accessory.find(@fight.accessory_2_id)
    @xp = @fight.strokes / 2
    @winner = Warrior.find_by_name(@fight.winner)
  end

  def new
    @fight = Fight.new
    @warriors = Warrior.all
  end

  def create
    @fight = Fight.new(fight_params)
    helpers.compute_outcome
    if @fight.valid?
      @fight.save
      Warrior.find_by_name(@fight.winner).update_xp(@fight.strokes) if @fight.winner != "Ex-aequo"
      redirect_to fight_path(@fight)
    else
      redirect_to root_path
    end
  end

  private

  def fight_params
    params.require(:fight).permit(:fighter_1_id, :fighter_2_id, :accessory_1_id, :accessory_2_id)
  end

  def set_fight
    @fight = Fight.find(params[:id])
  end

  def set_fighters
    @fighter_1 = Warrior.find(params["fight"]["fighter_1_id"].to_i)
    @fighter_2 = Warrior.find(params["fight"]["fighter_2_id"].to_i)
  end

  def set_accessories
    @accessory_1 = Accessory.find(params["fight"]["accessory_1_id"])
    @accessory_2 = Accessory.find(params["fight"]["accessory_2_id"])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @fight = Fight.new
    @warriors = Warrior.all
  end
end

app/controllers/warriors_controller.rb
class WarriorsController < ApplicationController
  before_action :set_warrior, only: [:show, :edit, :update, :destroy]

  def index
    @warriors = Warrior.all
  end

  def show
  end

  def new
    @warrior = Warrior.new
  end

  def create
    @warrior = Warrior.new(warrior_params)
    if @warrior.valid?
      @warrior.save
      redirect_to warriors_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @warrior.update(warrior_params)
    redirect_to warriors_path
  end

  def destroy
    @warrior.destroy
    redirect_to warriors_path
  end

  private

  def warrior_params
    params.require(:warrior).permit(:name, :intro, :avatar, :life_points, :strength)
  end

  def set_warrior
    @warrior = Warrior.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fights_helper.rb
module FightsHelper

  # each attack afflicts damages equal to strength, weighted by xp points and accessory as a weapon.
  # life points are updated if accessory is a shield
  def compute_outcome
    stroke_1 = 0
    stroke_2 = 0

    life_1 = compute_life_points(@fighter_1, @accessory_1)
    life_2 = compute_life_points(@fighter_2, @accessory_2)

    attack_1 = compute_attack_points(@fighter_1, @accessory_1)
    attack_2 = compute_attack_points(@fighter_2, @accessory_2)

    until life_1 <= 0 || life_2 <= 0 do
      life_2 -= (attack_1 * (1 + @fighter_1.xp * 0.01))
      stroke_1 += 1
      life_1 -= (attack_2 * (1 + @fighter_2.xp * 0.01))
      stroke_2 += 1
    end

    if life_1 == life_2
      winner = "Ex-aequo"
    elsif life_1 > life_2
      winner = @fighter_1.name
    else
      winner = @fighter_2.name
    end

    @fight.update(winner: winner, strokes: (stroke_1 + stroke_2))
  end

  def compute_life_points(warrior, accessory)
    if accessory.category == "shield"
      warrior.life_points + accessory.effect
    else
      warrior.life_points
    end
  end

  def compute_attack_points(warrior, accessory)
    if accessory.category == "weapon"
      warrior.strength * accessory.effect
    else
      warrior.strength
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper

 #get avatar with active storage
  def war_avatar(warrior)
    if warrior.avatar.attached?
      image_tag(warrior.avatar)
    end
  end

#return the name and number of victories of the best catfighter, used on fights#index
  def best_winner
    wins = Fight.all.group_by(&:winner).select{|k,v| k != "Ex-aequo"}.transform_values(&:count)
    if !wins.empty?
      return "The best catfighter is #{wins.max_by(&:last).first}, with #{wins.max_by(&:last).last} victories!"
    end
  end

#return the name and number of points of the most experienced fighter, used on fights#index
  def best_xp
    warrior = Warrior.all.max_by(&:xp)
    if warrior.xp != 0
      return "The most experienced fighter is #{warrior.name}, with #{warrior.xp} XP points."
    else
      return "Too soon to tell..."
    end
  end
end

app/views/fights/_new.html.erb
<h2>Start a new fight: </h2>

<div class="form">
  <%= simple_form_for @fight do |f| %>
    <div class="fighter-input">
      <%= f.input :fighter_1_id, collection: @warriors, label: "1st catfighter", include_blank: false %>
      <%= f.input :accessory_1_id, collection: Accessory.all, label: "Accessory", include_blank: false%>

    </div>
    <div class="fighter-input">
    <%= f.input :fighter_2_id, collection: @warriors, label: "2nd catfighter", include_blank: false %>
    <%= f.input :accessory_2_id, collection: Accessory.all,  label: "Accessory", include_blank: false%>
    </div>
    <br>
    <%= f.submit "Fight",input_html: {id: 'btn-submit'} %>
  <% end %>
</div>

app/views/fights/index.html.erb
<div class ="flex-container">

  <h2>Check out all fights:</h2>

  <div class="history-table">

    <strong> Date </strong>
    <strong> Fighter 1 </strong>
    <strong> Accessory 1 </strong>
    <strong> Fighter 2 </strong>
    <strong> Accessory 2 </strong>
    <strong> Attacks </strong>
    <strong> Winner </strong>

    <% if Fight.all.count != 0 %>
      <% @fights.each do |fight| %>
        <div><%= fight.created_at.to_date %> </div>
        <div>
          <%= fight.fighter_1.name%>
          <%=image_tag(fight.fighter_1.avatar, class: "avatar-small")%>
        </div>
        <div><%= fight.accessory_1.name %></div>
        <div>
          <%= fight.fighter_2.name %>
          <%=image_tag(fight.fighter_2.avatar, class: "avatar-small")%>
        </div>
        <div><%= fight.accessory_2.name %></div>
        <div><%= fight.strokes %></div>
        <div><%= fight.winner %></div>
      <% end %>
    <% end %>
  </div>

  <h2>Who's the best fighter ?:</h2>
  <% if Fight.all.count != 0 %>
    <%= best_winner %> <br>
    <%= best_xp %> <br>
  <% end %>

  <% if Fight.all.count == 0 %>
    <p class="text-centered">No fights registered yet...</p>
    <div class="center-items">
      <%= link_to "Start a fight!", root_path, class: "btn-action" %>
    </div>
  <% end %>


   <div class="center-items">
    <%= link_to "Back to Arena", root_path, class: "btn-back" %>
  </div>
</div>

app/views/fights/show.html.erb
<div class ="flex-container">

  <h2>And the winner is:</h2>

  <p class="text-centered"> Congrats! <br> <%= @fighter_1.name %> and  <%= @fighter_2.name %> fought very bravely. <br> After <%= @fight.strokes %> claw attacks exchanged, there might be only one survivor:  </p>

  <% if @fight.winner == "Ex-aequo" %>

    <h1> Ex-aequo </h1>
    <%= image_tag('claws.png', class: "avatar") %>
    <p class="text-centered"> Nobody wins, nobody get XP points...</p>

  <%else %>

    <h1> <%= @fight.winner %></h1>
    <%= image_tag(@winner.avatar, class: "avatar") %>
    <p class="text-centered"> <%= @winner.name %> wins <%= @xp %> XP points.</p>

  <% end %>

  <div class="center-items">
    <%= link_to "Back to Arena", root_path, class: "btn-action" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BattleFurry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('paw_print-512.png') %>
    <title>Battle Furry</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: radial-gradient(circle, rgba(238,147,55,1) 42%, rgba(133,12,12,1) 90%)">
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex-container">
  <h1>Welcome to Battle Furry</h1>

  <div class="intro">
    In today's world, mice, birds, even fishes are becoming increasingly rare... <br>
    Our cute little furry balls have to fight to win the attention of their hoomans and get fed! <br>
    You have now entered the Cats Arena. <br>
    Please select below two catfighters who will get the chance to be fed by you, or create your own pet.
  </div>

  <%= render 'fights/new' %>

  <div class="center-items">
    <%= link_to "Create a new Catfighter", new_warrior_path, class: "btn-action"  %>
    <%= link_to "See all Catfighters", warriors_path, class: "btn-action"  %>
    <%= link_to "See all Fights", fights_path, class: "btn-action"  %>
  </div>

</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <i> NB: No animals were harmed during the making of this app </i>
  <span> Made by Myriam Chah with <i class="fas fa-heart"></i> ! </span>
</footer>

app/views/warriors/edit.html.erb
<div class="flex-container">

  <h1>Edit a catfighter: </h1>

  <p class="text-centered"> Please update your catfighter:</p>
  <i class="hint text-centered">No, you cannot update XP points, that would be cheating ;)</i>

  <div class="form">
      <%= simple_form_for @warrior do |f| %>
        <%= f.input :name %>
        <%= f.input :intro %>
        <%= f.input :life_points, label: "Life points", placeholder: '0 - 200', input_html: { min: 0, max: 200, step: 'any' } %>
        <%= f.input :strength, label: "Attack points", collection: (0..10)%>
        <%= f.input :xp, disabled: true, label: "XP"%>
        <%= f.file_field :avatar %>
        <br>
        <%= f.submit "Update the Catfighter",input_html: {id: 'btn-submit'} %>
      <% end %>
  </div>

  <div class="center-items">
    <%= link_to "Back to all Catfighters", warriors_path, class: "btn-action"  %>
  </div>
  <div class="center-items">
    <%= link_to "Back to Arena", root_path, class: "btn-back" %>
  </div>
</div>

app/views/warriors/index.html.erb
<div class ="flex-container">

  <h2>Catfighters list :</h2>

  <% @warriors.each do |warrior| %>
    <div class="cat-card">
      <div> <%= war_avatar(warrior) %>
      </div>

      <div class="presentation">
        <span id="name"> <%= warrior.name %> </span>
        <br>
        <%= warrior.intro %>
      </div>

      <div class="characteristics">
        Life points: <%= warrior.life_points %>
        <br>
        Points of attack: <%= warrior.strength %>
        <br>
        Experience: <%= warrior.xp %>
      </div>

      <div class="icon">
        <%= link_to "<i class='far fa-eye'></i>".html_safe, warrior_path(warrior) %>
        <%= link_to "<i class='far fa-edit'></i>".html_safe, edit_warrior_path(warrior) %>
        <%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, warrior_path(warrior), method: :delete, :data => {:confirm => 'Are you sure?'}%>
      </div>
    </div>
  <% end %>

  <div class="center-items">
    <%= link_to "Create a new Catfighter", new_warrior_path, class: "btn-action" %>
  </div>
  <div class="center-items">
    <%= link_to "Back to Arena", root_path, class: "btn-back" %>
  </div>
</div>

app/views/warriors/new.html.erb
<div class="flex-container">

  <h1>New catfighter: </h1>
  <p class="text-centered"> Please fill all information regarding your catfighter:</p>

  <div class="form">
      <%= simple_form_for @warrior do |f| %>
        <%= f.input :name %>
        <%= f.input :intro %>
        <%= f.input :life_points, label: "Life points", placeholder: '0 - 200', input_html: { min: 0, max: 200, step: 'any' } %>
        <%= f.input :strength, label: "Attack points", collection: (0..10)%>
        <%= f.input :xp, disabled: true, label: "XP points" %>
        <%= f.file_field :avatar, input_html: {required: true } %>
        <br>
        <%= f.submit "Enter the arena",input_html: {id: 'btn-submit'} %>
      <% end %>
  </div>

  <div class="center-items">
    <%= link_to "Back to Arena", root_path, class: "btn-back" %>
  </div>
</div>

app/views/warriors/show.html.erb
<div class ="flex-container">

  <h1><%= @warrior.name %></h1>

  <div class="cat-sheet">

    <%= war_avatar(@warrior) %>

    <div class="presentation">
      <%= @warrior.intro %>
    </div>

    <h3>Characteristics: </h3>

    <div class="characteristics">
      Life points: <%= @warrior.life_points %>
      <br>
      Points of attack: <%= @warrior.strength %>
      <br>
      Experience: <%= @warrior.xp %>
    </div>

    <div class="icon">
      <%= link_to "<i class='far fa-edit'></i>".html_safe, edit_warrior_path(@warrior) %>
      <%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, warrior_path(@warrior), method: :delete, :data => {:confirm => 'Are you sure?'}%>
    </div>

    <h3>Performance: </h3>

    <div class="performance">
      Has fought  <%=@warrior.fights_nb %> times. <br>
      Won <%= @warrior.wins_nb %> fights! <br>
     Its victory rate is now <%= @warrior.wins_rate %> %! <br>
    </div>
  </div>

  <div class="center-items">
    <%= link_to "See all Catfighters", warriors_path, class: "btn-action"  %>
  </div>

  <div class="center-items">
    <%= link_to "Back to Arena", root_path, class: "btn-back" %>
  </div>
</div>